spring.application.name=notification-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5436/notificationdb
spring.datasource.username=notificationadmin
spring.datasource.password=notificationpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true