spring.application.name=order-servis

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5434/orderdb
spring.datasource.username=orderadmin
spring.datasource.password=orderpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=never
server.error.include-stacktrace=never
logging.level.com.it.orderservis=INFO

payment-service.url=http://localhost:8084