spring.application.name=order-servis

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5434/orderdb
spring.datasource.username=orderadmin
spring.datasource.password=orderpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=never
server.error.include-stacktrace=never
logging.level.com.it.orderservis=INFO

user-service.url=http://user-servis
product-service.url=http://product-servis
payment-service.url=http://payment-service
notification-service.url=http://notification-service


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true